framework: golang
version: 1.2.0
preRun:
  command:
    - "go get -d ./..."
    - "go get modernc.org/sqlite@latest"
    - "go mod vendor"

postMerge:
  pattern:
    # glob-patterns to discover tests to run in case of postMerge
    - ""
